	new Vue({
    el: '#app',
    data: {
    
        selected_my: '',

        regions_my : [
        		{
        			regionState: 'ရန်ကုန်တိုင်းဒေသကြီး', 
        			govName: 'ဖြိုးမင်းသိန်း'
        		},
        		{
        			regionState: 'မန္တလေးတိုင်းဒေသကြီး',
        			govName: 'ဇော်မြင့်မောင်'
        		},
        		{
        			regionState: 'ပဲခူးတိုင်းဒေသကြီး',
        			govName: 'ဦးဝင်းသိန်း'
        		},
        		{
        			regionState: 'ဧရာဝတီတိုင်းဒေသကြီး',
        			govName: 'ဦးလွမိုးေအာင္'
        		},
        		{
        			regionState: 'မကွေးတိုင်းဒေသကြီး',
        			govName: 'အောင်မိုးညို'
        		},
        		{
        			regionState: 'စစ်ကိုင်းတိုင်းဒေသကြီး‎',
        			govName: 'ဦးမြင့်နိုင်'
        		},
        		{
        			regionState: 'Tanintharyi Region',
        			govName: 'Le Le Maw'
        		},
        		{
        			regionState: 'Shan State',
        			govName: 'Dr Linn Htut'
        		},
        		{
        			regionState: 'Kayin State',
        			govName: 'Nan Khin Htwe Myint'
        		},
        		{
        			regionState: 'Mon State',
        			govName: 'Aye Zan, Dr'
        		},
                {
                    regionState: 'Rakhine State',
                    govName: 'Nyi Pu'
                },
                {
                    regionState: 'Chin State',
                    govName: 'Salai Lian Luai'
                },
                {
                    regionState: 'Kachin State',
                    govName: 'Dr Khat Aung'
                },
                {
                    regionState: 'Kayah State',
                    govName: 'L Phaung Sho'
                }
        ],
        
        list_my: '',

           optionsData_my: {
               Yangon: [
		                    { city: "Botataung"},  
							{ city: "DagonSeikkan"},
							{ city: "EastDagon"},
							{ city: "NorthDagon"},
							{ city: "NorthOkkalapa"},
							{ city: "Pazundaung"},
							{ city: "SouthDagon"},
							{ city: "SouthOkkalapa"},
							{ city: "Thingangyun"},
							{ city: "Dawbon"},
							{ city: "MingalaTaungnyunt"},
							{ city: "Tamwe"},
							{ city: "Thaketa"},
							{ city: "Yankin"},
							{ city: "Hlaingthaya"},
							{ city: "Insein"},
							{ city: "Mingaladon"},
							{ city: "Shwepyitha"},
							{ city: "Hlegu"},
							{ city: "Hmawbi"},
							{ city: "Htantabin"},
							{ city: "Taikkyi"},
							{ city: "Dala"},
							{ city: "SeikkyiKanaungto"},
							{ city: "Cocokyun"},
							{ city: "Kawhmu"},
							{ city: "Kayan"},
							{ city: "Kungyangon"},
							{ city: "Kyauktan"},
							{ city: "Thanlyin"},
							{ city: "Thongwa"},
							{ city: "Twante"},
							{ city: "TadaSub"},
							{ city: "Ahlon"},
							{ city: "Bahan"},
							{ city: "Dagon"},
							{ city: "Kyauktada"},
							{ city: "Kyimyindaing"},
							{ city: "Lanmadaw"},
							{ city: "Latha"},
							{ city: "Pabedan"},
							{ city: "Sanchaung"},
							{ city: "Seikkan"},
							{ city: "Hlaing"},
							{ city: "Kamayut"},
							{ city: "Mayangon"},
							{ city: "Hlegu"},
							{ city: "Kawhmu"},
							{ city: "Kyauktan"},
							{ city: "Taikkyi"},
							{ city: "Thongwa"},
							{ city: "Thanlyin"},
							{ city: "Twante"}
               ],
               
               Mandalay: [
                   			{ city:'Aung Myay Thar Zan'},
							{ city:'Chan Aye Thar Zan'},
							{ city:'Mahar Aung Myay'},
							{ city:'Chan Mya Thar Si'},
							{ city:'Pyi Gyi Tan Kon'},
							{ city:'Amarapura'},
							{ city:'Pa Thein Gyi'},
							{ city:'Nay Pyi Taw'},
							{ city:'Pyinmana'},
							{ city:'Tatkon'},
							{ city:'Lewe'},
							{ city:'Dekkhinathiri'},
							{ city:'Ottarathiri'},
							{ city:'Pobbathiri'},
							{ city:'Zabuthiri'},
							{ city:'Zeyathiri'},
							{ city:'Pyin Oo Lwin'},
							{ city:'Madaya'},
							{ city:'Singu'},
							{ city:'Thabeikkyin'},
							{ city:'Mogok'},
							{ city:'Kyaukpadaung'},
							{ city:'Kyaukse'},
							{ city:'Sintgaing'},
							{ city:'Myittha'},
							{ city:'Tada-U'},
							{ city:'Myingyan'},
							{ city:'Thaungtha'},
							{ city:'Natogyi'},
							{ city:'Nyaung-U'},
							{ city:'Meiktila'},
							{ city:'Mahlaing'},
							{ city:'Thazi'},
							{ city:'Wundwin'},
							{ city:'Pyawbwe'},
							{ city:'Yamethin'},
               ],
               Bago: [
				            { city:'Bago'},
					        { city:'Daik-U'},
					        { city:'Kawa'},
					        { city:'Thanatpin'},
					        { city:'Waw'},
					        { city:'Nyaunglebin'},
					        { city:'Shwegyin'},
					        { city:'Pyay'},
					        { city:'Paukkaung'},
					        { city:'Thegon'},
					        { city:'Shwedaung'},
					        { city:'Padaung'},
					        { city:'Paungde'},
					        { city:'Nattalin'},
					        { city:'Zigon'},
					        { city:'Tharrawaddy'},
					        { city:'Gyobingauk'},
					        { city:'Letpadan'},
					        { city:'Minhla'},
					        { city:'Monyo'},
					        { city:'Okpho'},
					        { city:'Taungoo'},
					        { city:'Oktwin'},
					        { city:'Tantabin'},
					        { city:'Yedashe'},
					        { city:'Pyu'},
					        { city:'Kyauktaga'},
					        { city:'Kyaukkyi'},
					        { city:'Hpa Yar Gyi'},
               ],
               Ayeyarwady: [
                    		{ city:'Bogale'},
                    		{ city:'Danubyu'},
                    		{ city:'Einme'},
                    		{ city:'Hinthada'},
                    		{ city:'Ingapu'},
                    		{ city:'Kangyidaunt'},
                    		{ city:'Kyaiklat'},
                    		{ city:'Kyangin'},
                    		{ city:'Kyaunggon'},
                    		{ city:'Kyonpyaw'},
                    		{ city:'Labutta'},
                    		{ city:'Lemyethna'},
                    		{ city:'Maubin'},
                    		{ city:'Mawlamyinegyun(Mawgyun)'},
                    		{ city:'Myanaung'},
                    		{ city:'Myaungmya'},
                    		{ city:'Ngapudaw'},
                    		{ city:'Nyaungdon'},
                    		{ city:'Pantanaw'},
                    		{ city:'Pathein'},
                    		{ city:'Pyapon'},
                    		{ city:'Thabaung'},
                    		{ city:'Wakema'},
                    		{ city:'Yegyi'},
                    		{ city:'Zalun'},
               ],
               Magway : [
               				{ city:'Aunglan'},
                    		{ city:'Chauk'},
                    		{ city:'Gangaw'},
                    		{ city:'Kamma'},
                    		{ city:'Magway'},
                    		{ city:'Minbu'},
                    		{ city:'Mindon'},
                    		{ city:'Minhla'},
                    		{ city:'Myaing'},
                    		{ city:'Myothit'},
                    		{ city:'Natmauk'},
                    		{ city:'Ngape'},
                    		{ city:'Pakokku'},
                    		{ city:'Pauk'},
                    		{ city:'Pwintbyu'},
                    		{ city:'Salin'},
                    		{ city:'Saw'},
                    		{ city:'Seikphyu'},
                    		{ city:'Sidoktaya'},
                    		{ city:'Sinbaungwe'},
                    		{ city:'Taungdwingyi'},
                    		{ city:'Thayet'},
                    		{ city:'Tilin'},
                    		{ city:'Yenangyaung'},
                    		{ city:'Yesagyo'},
               ],
               Sagaing : [
                    		{ city:'Sagaing'},
                    		{ city:'Monywa'},
                    		{ city:'Shwebo'},
                    		{ city:'Tabayin'},
                    		{ city:'Katha'},
                    		{ city:'Ayadaw'},
                    		{ city:'Banmauk'},
                    		{ city:'Budalin'},
                    		{ city:'Chaung-U'},
                    		{ city:'Hkamti'},
                    		{ city:'Homalin'},
                    		{ city:'Indaw'},
                    		{ city:'Kale'},
                    		{ city:'Kalewa'},
                    		{ city:'kanbalu'},
                    		{ city:'Kani'},
                    		{ city:'Kawlin'},
                    		{ city:'Khin-U'},
                    		{ city:'Kyunhla'},
                    		{ city:'Lahe'},
                    		{ city:'Mawlaik'},
                    		{ city:'Mingin'},
                    		{ city:'Myaung'},
                    		{ city:'Myinmu'},
                    		{ city:'Nanyun'},
                    		{ city:'Pale'},
                    		{ city:'Paungbyin'},
                    		{ city:'Pinlebu'},
                    		{ city:'Salingyi'},
                    		{ city:'Tamu'},
                    		{ city:'Taze'},
                    		{ city:'Tigyaing'},
                    		{ city:'Wetlet'},
                    		{ city:'Wuntho'},
                    		{ city:'Ye-U'},
                    		{ city:'Yinmabin'},
               ],
               Tanintharyi : [
               				{ city:'Dawei'},
                   			{ city:'Kawthoung'},
                   			{ city:'Myeik'},
                   			{ city:'Bokpyin'},
                   			{ city:'Kyunsu'},
                   			{ city:'Palaw'},
                   			{ city:'Tanintharyi'},
                   			{ city:'Thayetchaung'},
                   			{ city:'Yebyu'},
               ],
               Shan : [               		
                    		{ city:'Taunggyi'},
                    		{ city:'Kengtung'},
                    		{ city:'Tachileik'},
                    		{ city:'Hsipaw'},
                    		{ city:'Kyuakme'},
                    		{ city:'Lashio'},
                    		{ city:'Muse'},
                    		{ city:'Nawnghkio'},
                    		{ city:'Hopong'},
                    		{ city:'Kalaw'},
                    		{ city:'Loilen'},
                    		{ city:'Nyaungshwe'},
                    		{ city:'Pindaya'},
                    		{ city:'Pinlaung'},
                    		{ city:'Matman'},
                    		{ city:'Monghpyak'},
                    		{ city:'Monghsat'},
                    		{ city:'Mongkhet'},
                    		{ city:'Mongla'},
                    		{ city:'Mongping'},
                    		{ city:'Mongton'},
                    		{ city:'Mongyang'},
                    		{ city:'Mongyawng'},
                    		{ city:'Hopang'},
                    		{ city:'Hseni'},
                    		{ city:'Konkyan'},
                    		{ city:'Kunlong'},
                    		{ city:'Kutkai'},
                    		{ city:'Laukkaing'},
                    		{ city:'Mabein'},
                    		{ city:'Mongmao'},
                    		{ city:'Mongmit'},
                    		{ city:'Mongyai'},
                    		{ city:'Namhsan'},
                    		{ city:'Namtu'},
                    		{ city:'Nanhkan'},
                    		{ city:'Pangsang'},
                    		{ city:'Pangwaun'},
                    		{ city:'Tangyan'},
                    		{ city:'Hsihseng'},
                    		{ city:'Kunhing'},
                    		{ city:'Kyethi'},
                    		{ city:'Laihka'},
                    		{ city:'Laihka'},
                    		{ city:'Lawksawk'},
                    		{ city:'Mawkmai'},
                    		{ city:'Monghsu'},
                    		{ city:'Mongkaung'},
                    		{ city:'Mongnai'},
                    		{ city:'Mongpan'},
                    		{ city:'Nansang'},
                    		{ city:'Pekon'},
                    		{ city:'Ywangan'},
               ],
               Kayin : [
               				{ city:'Hpa-An'},
                    		{ city:'Kawkareik'},
                    		{ city:'Myawaddy'},
                    		{ city:'Thandaung'},
                    		{ city:'Hlaingbwe'},
                    		{ city:'Hpapun'},
                    		{ city:'Kyain Seikgyi'},
               ],

               Mon : [
               				{ city: 'Kyaikto'},
                    		{ city: 'Mawlamyine'},
                    		{ city: 'Thaton'},
                    		{ city: 'Bilin'},
                    		{ city: 'Chaungzon'},
                    		{ city: 'Kyaikmaraw'},
                    		{ city: 'Mudon'},
                    		{ city: 'Thanbyuzayat'},
                    		{ city: 'Paung'},
                    		{ city: 'Ye'},
               ],
               Rakhin : [
                            { city: 'Sittwe'},
                            { city: 'Thandwe'},
                            { city: 'Toungup'},
                            { city: 'Ann'},
                            { city: 'Buthidaung'},
                            { city: 'Gwa'},
                            { city: 'Kyaukpyu'},
                            { city: 'Kyauktaw'},
                            { city: 'Maungdaw'},
                            { city: 'Minbya'},
                            { city: 'Mrauk-U'},
                            { city: 'Munaung'},
                            { city: 'Myebon'},
                            { city: 'Pauktaw'},
                            { city: 'Ponnagyun'},
                            { city: 'Ramree'},
                            { city: 'Rathedaung'},
               ],
               Chin : [
                            { city: 'Hakha'},
                            { city: 'Mindat'},
                            { city: 'Falam'},
                            { city: 'Htantlang'},
                            { city: 'Kanpetlet'},
                            { city: 'Madupi'},
                            { city: 'Paletwa'},
                            { city: 'Tiddim'},
                            { city: 'Tonzang'},
               ],
               Kachin : [
                            { city: 'Myitkyina'},
                            { city: 'Puta-O'},
                            { city: 'Bhamo'},
                            { city: 'Hpakan'},
                            { city: 'Mogaung'},
                            { city: 'Mohnyin'},
                            { city: 'Momauk'},
                            { city: 'Shwegu'},
                            { city: 'Injangyang'},
                            { city: 'Kawnglanghpu'},
                            { city: 'Machanbaw'},
                            { city: 'Mansi'},
                            { city: 'Nogmung'},
                            { city: 'Sumprabum'},
                            { city: 'Tanai'},
                            { city: 'Tsawlaw'},
                            { city: 'Waingmaw'},
               ],
               Kayah : [
                            { city: 'Loikaw'},
                            { city: 'Bawlakhe'},
                            { city: 'Demoso'},
                            { city: 'Hpasawng'},
                            { city: 'Hpruso'},
                            { city: 'Mese'},
                            { city: 'Shadaw'},
               ],
                 All:    [
                                   { city: "Botataung"},  
                                   { city: "DagonSeikkan"},
                                   { city: "EastDagon"},
                                   { city: "NorthDagon"},
                                   { city: "NorthOkkalapa"},
                                   { city: "Pazundaung"},
                                   { city: "SouthDagon"},
                                   { city: "SouthOkkalapa"},
                                   { city: "Thingangyun"},
                                   { city: "Dawbon"},
                                   { city: "MingalaTaungnyunt"},
                                   { city: "Tamwe"},
                                   { city: "Thaketa"},
                                   { city: "Yankin"},
                                   { city: "Hlaingthaya"},
                                   { city: "Insein"},
                                   { city: "Mingaladon"},
                                   { city: "Shwepyitha"},
                                   { city: "Hlegu"},
                                   { city: "Hmawbi"},
                                   { city: "Htantabin"},
                                   { city: "Taikkyi"},
                                   { city: "Dala"},
                                   { city: "SeikkyiKanaungto"},
                                   { city: "Cocokyun"},
                                   { city: "Kawhmu"},
                                   { city: "Kayan"},
                                   { city: "Kungyangon"},
                                   { city: "Kyauktan"},
                                   { city: "Thanlyin"},
                                   { city: "Thongwa"},
                                   { city: "Twante"},
                                   { city: "TadaSub"},
                                   { city: "Ahlon"},
                                   { city: "Bahan"},
                                   { city: "Dagon"},
                                   { city: "Kyauktada"},
                                   { city: "Kyimyindaing"},
                                   { city: "Lanmadaw"},
                                   { city: "Latha"},
                                   { city: "Pabedan"},
                                   { city: "Sanchaung"},
                                   { city: "Seikkan"},
                                   { city: "Hlaing"},
                                   { city: "Kamayut"},
                                   { city: "Mayangon"},
                                   { city: "Hlegu"},
                                   { city: "Kawhmu"},
                                   { city: "Kyauktan"},
                                   { city: "Taikkyi"},
                                   { city: "Thongwa"},
                                   { city: "Thanlyin"},
                                   { city: "Twante"},
                                   { city:'Aung Myay Thar Zan'},
                                   { city:'Chan Aye Thar Zan'},
                                   { city:'Mahar Aung Myay'},
                                   { city:'Chan Mya Thar Si'},
                                   { city:'Pyi Gyi Tan Kon'},
                                   { city:'Amarapura'},
                                   { city:'Pa Thein Gyi'},
                                   { city:'Nay Pyi Taw'},
                                   { city:'Pyinmana'},
                                   { city:'Tatkon'},
                                   { city:'Lewe'},
                                   { city:'Dekkhinathiri'},
                                   { city:'Ottarathiri'},
                                   { city:'Pobbathiri'},
                                   { city:'Zabuthiri'},
                                   { city:'Zeyathiri'},
                                   { city:'Pyin Oo Lwin'},
                                   { city:'Madaya'},
                                   { city:'Singu'},
                                   { city:'Thabeikkyin'},
                                   { city:'Mogok'},
                                   { city:'Kyaukpadaung'},
                                   { city:'Kyaukse'},
                                   { city:'Sintgaing'},
                                   { city:'Myittha'},
                                   { city:'Tada-U'},
                                   { city:'Myingyan'},
                                   { city:'Thaungtha'},
                                   { city:'Natogyi'},
                                   { city:'Nyaung-U'},
                                   { city:'Meiktila'},
                                   { city:'Mahlaing'},
                                   { city:'Thazi'},
                                   { city:'Wundwin'},
                                   { city:'Pyawbwe'},
                                   { city:'Yamethin'},
                                   { city:'Bago'},
                                   { city:'Daik-U'},
                                   { city:'Kawa'},
                                   { city:'Thanatpin'},
                                   { city:'Waw'},
                                   { city:'Nyaunglebin'},
                                   { city:'Shwegyin'},
                                   { city:'Pyay'},
                                   { city:'Paukkaung'},
                                   { city:'Thegon'},
                                   { city:'Shwedaung'},
                                   { city:'Padaung'},
                                 { city:'Paungde'},
                                 { city:'Nattalin'},
                                 { city:'Zigon'},
                                 { city:'Tharrawaddy'},
                                 { city:'Gyobingauk'},
                                 { city:'Letpadan'},
                                 { city:'Minhla'},
                                 { city:'Monyo'},
                                 { city:'Okpho'},
                                 { city:'Taungoo'},
                                 { city:'Oktwin'},
                                 { city:'Tantabin'},
                                 { city:'Yedashe'},
                                 { city:'Pyu'},
                                 { city:'Kyauktaga'},
                                 { city:'Kyaukkyi'},
                                 { city:'Hpa Yar Gyi'},
                              { city:'Bogale'},
                              { city:'Danubyu'},
                              { city:'Einme'},
                              { city:'Hinthada'},
                              { city:'Ingapu'},
                              { city:'Kangyidaunt'},
                              { city:'Kyaiklat'},
                              { city:'Kyangin'},
                              { city:'Kyaunggon'},
                              { city:'Kyonpyaw'},
                              { city:'Labutta'},
                              { city:'Lemyethna'},
                              { city:'Maubin'},
                              { city:'Mawlamyinegyun(Mawgyun)'},
                              { city:'Myanaung'},
                              { city:'Myaungmya'},
                              { city:'Ngapudaw'},
                              { city:'Nyaungdon'},
                              { city:'Pantanaw'},
                              { city:'Pathein'},
                              { city:'Pyapon'},
                              { city:'Thabaung'},
                              { city:'Wakema'},
                              { city:'Yegyi'},
                              { city:'Zalun'},
                                   { city:'Aunglan'},
                              { city:'Chauk'},
                              { city:'Gangaw'},
                              { city:'Kamma'},
                              { city:'Magway'},
                              { city:'Minbu'},
                              { city:'Mindon'},
                              { city:'Minhla'},
                              { city:'Myaing'},
                              { city:'Myothit'},
                              { city:'Natmauk'},
                              { city:'Ngape'},
                              { city:'Pakokku'},
                              { city:'Pauk'},
                              { city:'Pwintbyu'},
                              { city:'Salin'},
                              { city:'Saw'},
                              { city:'Seikphyu'},
                              { city:'Sidoktaya'},
                              { city:'Sinbaungwe'},
                              { city:'Taungdwingyi'},
                              { city:'Thayet'},
                              { city:'Tilin'},
                              { city:'Yenangyaung'},
                              { city:'Yesagyo'},
                              { city:'Sagaing'},
                              { city:'Monywa'},
                              { city:'Shwebo'},
                              { city:'Tabayin'},
                              { city:'Katha'},
                              { city:'Ayadaw'},
                              { city:'Banmauk'},
                              { city:'Budalin'},
                              { city:'Chaung-U'},
                              { city:'Hkamti'},
                              { city:'Homalin'},
                              { city:'Indaw'},
                              { city:'Kale'},
                              { city:'Kalewa'},
                              { city:'kanbalu'},
                              { city:'Kani'},
                              { city:'Kawlin'},
                              { city:'Khin-U'},
                              { city:'Kyunhla'},
                              { city:'Lahe'},
                              { city:'Mawlaik'},
                              { city:'Mingin'},
                              { city:'Myaung'},
                              { city:'Myinmu'},
                              { city:'Nanyun'},
                              { city:'Pale'},
                              { city:'Paungbyin'},
                              { city:'Pinlebu'},
                              { city:'Salingyi'},
                              { city:'Tamu'},
                              { city:'Taze'},
                              { city:'Tigyaing'},
                              { city:'Wetlet'},
                              { city:'Wuntho'},
                              { city:'Ye-U'},
                              { city:'Yinmabin'},
                                   { city:'Dawei'},
                              { city:'Kawthoung'},
                              { city:'Myeik'},
                              { city:'Bokpyin'},
                              { city:'Kyunsu'},
                              { city:'Palaw'},
                              { city:'Tanintharyi'},
                              { city:'Thayetchaung'},
                              { city:'Yebyu'},            
                              { city:'Taunggyi'},
                              { city:'Kengtung'},
                              { city:'Tachileik'},
                              { city:'Hsipaw'},
                              { city:'Kyuakme'},
                              { city:'Lashio'},
                              { city:'Muse'},
                              { city:'Nawnghkio'},
                              { city:'Hopong'},
                              { city:'Kalaw'},
                              { city:'Loilen'},
                              { city:'Nyaungshwe'},
                              { city:'Pindaya'},
                              { city:'Pinlaung'},
                              { city:'Matman'},
                              { city:'Monghpyak'},
                              { city:'Monghsat'},
                              { city:'Mongkhet'},
                              { city:'Mongla'},
                              { city:'Mongping'},
                              { city:'Mongton'},
                              { city:'Mongyang'},
                              { city:'Mongyawng'},
                              { city:'Hopang'},
                              { city:'Hseni'},
                              { city:'Konkyan'},
                              { city:'Kunlong'},
                              { city:'Kutkai'},
                              { city:'Laukkaing'},
                              { city:'Mabein'},
                              { city:'Mongmao'},
                              { city:'Mongmit'},
                              { city:'Mongyai'},
                              { city:'Namhsan'},
                              { city:'Namtu'},
                              { city:'Nanhkan'},
                              { city:'Pangsang'},
                              { city:'Pangwaun'},
                              { city:'Tangyan'},
                              { city:'Hsihseng'},
                              { city:'Kunhing'},
                              { city:'Kyethi'},
                              { city:'Laihka'},
                              { city:'Laihka'},
                              { city:'Lawksawk'},
                              { city:'Mawkmai'},
                              { city:'Monghsu'},
                              { city:'Mongkaung'},
                              { city:'Mongnai'},
                              { city:'Mongpan'},
                              { city:'Nansang'},
                              { city:'Pekon'},
                              { city:'Ywangan'},
                              { city:'Hpa-An'},
                              { city:'Kawkareik'},
                              { city:'Myawaddy'},
                              { city:'Thandaung'},
                              { city:'Hlaingbwe'},
                              { city:'Hpapun'},
                              { city:'Kyain Seikgyi'},
                              { city: 'Kyaikto'},
                              { city: 'Mawlamyine'},
                              { city: 'Thaton'},
                              { city: 'Bilin'},
                              { city: 'Chaungzon'},
                              { city: 'Kyaikmaraw'},
                              { city: 'Mudon'},
                              { city: 'Thanbyuzayat'},
                              { city: 'Paung'},
                              { city: 'Ye'},
                            { city: 'Sittwe'},
                            { city: 'Thandwe'},
                            { city: 'Toungup'},
                            { city: 'Ann'},
                            { city: 'Buthidaung'},
                            { city: 'Gwa'},
                            { city: 'Kyaukpyu'},
                            { city: 'Kyauktaw'},
                            { city: 'Maungdaw'},
                            { city: 'Minbya'},
                            { city: 'Mrauk-U'},
                            { city: 'Munaung'},
                            { city: 'Myebon'},
                            { city: 'Pauktaw'},
                            { city: 'Ponnagyun'},
                            { city: 'Ramree'},
                            { city: 'Rathedaung'},
                            { city: 'Hakha'},
                            { city: 'Mindat'},
                            { city: 'Falam'},
                            { city: 'Htantlang'},
                            { city: 'Kanpetlet'},
                            { city: 'Madupi'},
                            { city: 'Paletwa'},
                            { city: 'Tiddim'},
                            { city: 'Tonzang'},
                            { city: 'Myitkyina'},
                            { city: 'Puta-O'},
                            { city: 'Bhamo'},
                            { city: 'Hpakan'},
                            { city: 'Mogaung'},
                            { city: 'Mohnyin'},
                            { city: 'Momauk'},
                            { city: 'Shwegu'},
                            { city: 'Injangyang'},
                            { city: 'Kawnglanghpu'},
                            { city: 'Machanbaw'},
                            { city: 'Mansi'},
                            { city: 'Nogmung'},
                            { city: 'Sumprabum'},
                            { city: 'Tanai'},
                            { city: 'Tsawlaw'},
                            { city: 'Waingmaw'},
                            { city: 'Loikaw'},
                            { city: 'Bawlakhe'},
                            { city: 'Demoso'},
                            { city: 'Hpasawng'},
                            { city: 'Hpruso'},
                            { city: 'Mese'},
                            { city: 'Shadaw'},
               ]
           }
       },
       
    //    computed: {
       
    //        options: function() {
           
    //        let options = ''

    //             switch(this.selected.value) {

    //                 case 'Yangon':
    //                 options = this.optionsData.Yangon
    //                 break;
                    
    //                 case 'Mandalay':
    //                 options = this.optionsData.Mandalay
    //                 break;

    //                 case 'Bago Region':
    //                 options = this.optionsData.Bago
    //                 break;

    //                 case 'Ayeyarwady':
    //                 options = this.optionsData.Sagaing
    //                 break;

    //                 case 'Bago':
    //                 options = this.optionsData.Bago
    //                 break;

    //                 case 'Ayeyarwady Region':
    //                 options = this.optionsData.Ayeyarwady
    //                 break;

    //                 case 'Magway Region':
    //                 options = this.optionsData.Magway
    //                 break;

    //                 case 'Sagaing Region':
    //                 options = this.optionsData.Sagaing
    //                 break;

    //                 case 'Tanintharyi Region':
    //                 options = this.optionsData.Tanintharyi
    //                 break;

    //                 case 'Shan State':
    //                 options = this.optionsData.Shan
    //                 break;

    //                 case 'Kayin State':
    //                 options = this.optionsData.Kayin
    //                 break;

    //                 case 'Mon State':
    //                 options = this.optionsData.Mon
    //                 break;

    //                 case 'Rakhine State':
    //                 options = this.optionsData.Rakhin
    //                 break;

    //                 case 'Chin State':
    //                 options = this.optionsData.Chin
    //                 break;

    //                 case 'Kachin State':
    //                 options = this.optionsData.Kachin
    //                 break;

    //                 case 'Kayah State':
    //                 options = this.optionsData.Kayah
    //                 break;

    //                 default:
    //                 options = this.optionsData.All
    //             }

    //             return options
           
    //        }
       
    //    },
       
    //    methods: {
       
    //      onChange: function ()
    //      {
    //          this.options = this.options
    //      }
         
    // }

})